---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

dataSource:
    pooled: true
    jmxExport: true

environments:
    development:
        dataSource:
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            dbCreate: update
            url: jdbc:mysql://localhost:3306/database?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true
            username: username
            password: password
    test:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            dbCreate: update
            url: jdbc:mysql://localhost/database?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true
            username: username
            password: password
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
---
grails:
    plugin:
        springsecurity:
            userLookup.userDomainClassName: 'pl.emisoft.microservices.kropek.users.User'
            userLookup.authorityJoinClassName: 'pl.emisoft.microservices.kropek.users.UserRole'
            useSecurityEventListener: true
            authority.className: 'pl.emisoft.microservices.kropek.users.Role'
            securityConfigType: 'InterceptUrlMap'
            interceptUrlMap:
                - {pattern: '/', access: ['permitAll']}
                - {pattern: '/error', access: ['permitAll']}
                - {pattern: '/index', access: ['permitAll']}
                - {pattern: '/index.gsp', access: ['permitAll']}
                - {pattern: '/shutdown', access: ['permitAll']}
                - {pattern: '/assets/**', access: ['permitAll']}
                - {pattern: '/**/js/**', access: ['permitAll']}
                - {pattern: '/**/css/**', access: ['permitAll']}
                - {pattern: '/**/images/**', access: ['permitAll']}
                - {pattern: '/**/favicon.ico', access: ['permitAll']}
            controllerAnnotations.staticRules:
                - {pattern: '/', access: ['permitAll']}
                - {pattern: '/error', access: ['permitAll']}
                - {pattern: '/index', access: ['permitAll']}
                - {pattern: '/index.gsp', access: ['permitAll']}
                - {pattern: '/shutdown', access: ['permitAll']}
                - {pattern: '/assets/**', access: ['permitAll']}
                - {pattern: '/**/js/**', access: ['permitAll']}
                - {pattern: '/**/css/**', access: ['permitAll']}
                - {pattern: '/**/images/**', access: ['permitAll']}
                - {pattern: '/**/favicon.ico', access: ['permitAll']}
            filterChain.chainMap:
                - {pattern: '/assets/**', filters: 'none'}
                - {pattern: '/**/js/**', filters: 'none'}
                - {pattern: '/**/css/**', filters: 'none'}
                - {pattern: '/**/images/**', filters: 'none'}
                - {pattern: '/**/favicon.ico', filters: 'none'}
                - {pattern: '/api/**', filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'}
